### ISSUE TITLE
OpenGL Error: out of memory(1285)

### ISSUE THREAD

**Issue by szm88** [jbehley/SuMa#1]
when i run visualizer, i got error:
Extracting surfel maps partially.
OpenGL Error: out of memory(1285)
In: /home/***/catkin_ws/src/SuMa/src/core/SurfelMap.cpp on Line: 298
terminate called after throwing an instance of 'std::runtime_error'
  what():  OpenGL error detected.
Aborted (core dumped)

**Comment by jbehley** [comment]
It seems like that your GPU has unfortunately not enough memory  available. I would recommend to have something like at least 2 GB dedicated memory for running the program. (On my notebook with a Geforce 860m and 2 GB of dedicated memory, it works fine. At some point it ran also with the integrated Intel GPU, but I didn't test this recently.)

You can try to reduce the needed memory by adjusting in the file ```config/default.xml``` the history size, i.e.,
```xml 
   <param name="history size" type="integer">10</param>
```
this will reduce the number of scans used to show the history.

Furthermore, you can reduce the needed memory by adjusting the variable ```maxNumSurfels_``` in the `SurfelMap.h`, but might then lose some surfels on the way.

These are the main points to reduce the amount of needed memory. However, we never had memory consumption as a main direction of optimization. There are certainly some textures in some other parts, which are not used at all and therefore could be deleted.

As always, this is research code and therefore at some points not really optimized.
