### ISSUE TITLE
what is the difference between these five images

### ISSUE THREAD

**Issue by zorosmith** [jbehley/SuMa#21]
Hello, I think that Fig.1(left and right), Fig.2 and Fig.4 are normal map.
Fig.3 and Fig.5 are vertex map(depth map).
I found that Fig.4 and Fig.5 are the current normal map(N_{D}) and vertex map(V_{D}) respectively. 
And I guess that Fig.2 and Fig.3 are the rendered normal map(N_{M}) and vertex map(V_{M}) respectively. Because I found that the dynamic objects had been filtered from the Fig.2 and Fig.3.
There is no label beside to the images, which makes me confused.
Plz point out if I didn't understand it correctly!

![image](https://user-images.githubusercontent.com/22607041/75629365-7cbfb680-5c1c-11ea-824a-8db03d458795.png)

**Comment by jbehley** [comment]
The images are mainly for debugging, therefore I did not spend much time on making it self explanatory.
Your almost correct with your analysis, here captions:

![image](https://user-images.githubusercontent.com/11506664/75931713-e71f6380-5e75-11ea-8a1a-5db5026b7055.png)

there first row shows the normal maps of the rendered model considering surfels with different timestamps. the left image is the view with only old surfels. These are needed for loop closure detection.
