### ISSUE TITLE
Question about the getConfidenceThreshold() in SurfelMapping.cpp？

### ISSUE THREAD

**Issue by Gatsby23** [jbehley/SuMa#27]
I'm confused about the confidence calculation in SurfelMapping.cpp, which used for SurfelMap->render();
![image](https://user-images.githubusercontent.com/18000675/89534231-330c7500-d827-11ea-872b-0a4d27a28a55.png) Are there some reference about this confidence calculation ？I'm sorry to bothering you about this, but I really search for your paper and some references about it, but I still confused about it. I'd really appreiciate it for your help!

**Comment by jbehley** [comment]
Sorry that I forgot to answer. This is a "hack" to ensure that initially surfels are not just removed (the time_init number of frames). Therefore, I simply increase linearly the threshold from log_unstable_ to the confidence_threshold.
