### ISSUE TITLE
Used in stereo camera

### ISSUE THREAD

**Issue by liuzhenboo** [jbehley/SuMa#30]
Can this project be expanded for outdoor reconstruction of binocular cameras？

**Comment by jbehley** [comment]
I would guess with some modifications to the projection function, it should be possible. 

The only thing that our algorithm needs is a vertex map and normal map (which is generated from the vertex map) and a projection function to get from three-dimensional points to the image coordinates in these vertex and normal maps.

**Comment by liuzhenboo** [comment]
> I would guess with some modifications to the projection function, it should be possible.
> 
> The only thing that our algorithm needs is a vertex map and normal map (which is generated from the vertex map) and a projection function to get from three-dimensional points to the image coordinates in these vertex and normal maps.

Thanks a lot, I will try it!
