### ISSUE TITLE
Questions on the equation (10) in the paper

### ISSUE THREAD

**Issue by Tompson11** [jbehley/SuMa#31]
Hi!
Thank you for sharing your work!
I have a question on the equation (10) in your paper. According to your definition of the _clamp_ , the denominator of (10) is always 0.5 since the first term(a cos value within [-1,1]) in clamp is always less than the third term. I wonder if I have any misunderstanding here.
![image](https://user-images.githubusercontent.com/42952053/104326067-3f0e0880-5524-11eb-8456-34431ab86b16.png)

**Comment by jbehley** [comment]
Sorry for the late answer.

That's correct, the definition should be `clamp(x,l,u)` and it was intended to have values inbetween 0.5 and 1.0. Thanks for noticing the error in the definition.

hope that clarifies your question.
