### ISSUE TITLE
 segmentation fault 

### ISSUE THREAD

**Issue by hungkyun** [jbehley/SuMa#32]
two days ago i successfully built and use for pose estimation,but today it turns to segmentation fault,here's the gdb imformation:
 Program received signal SIGSEGV, Segmentation fault.
__GI___libc_free (mem=0x20) at malloc.c:3113
3113	malloc.c. no such or directory.

i met seg fault for the very beginning and i"get gtsam version 4.0.0-alpha2 and try it with GTSAM_USE_SYSTEM_EIGEN activated."to solve the problem.

hope that somthing wrong can be found.

**Comment by jbehley** [comment]
It would maybe help to see the complete backtrack and to get an idea, where the error originates. Currently, I can only deduce that there is an error in freeing memory.

**Comment by hungkyun** [comment]
it works after i rebuild the gtsam and suma like before,thank you for helpping!

**Comment by xdtzzz** [comment]
hi, I meet the same problem with you , and I add GTSAM_USE_SYSTEM_EIGEN ON in gtsam cmakelist.txt, but it doesn't work.   i am gtsam4.0.0-alpha2, eigen3.4.0, I can run SuMa++, but doesn't work SuMa, could you help me?  @hungkyun
