### ISSUE TITLE
Try to understand the file pose.txt

### ISSUE THREAD

**Issue by John155** [jbehley/SuMa#39]
Hi,

I try to understand the pose.txt file. If I look inside the file, each row has 12 items.

For example: 0.999932 -0.0110913 0.00372999 0.132322 0.0110829 0.999936 0.00228526 0.0384668 -0.0037551 -0.00224376 0.99999 0.0203489

My question is: what represent the 12 entries?

**Comment by jbehley** [comment]
These values are the row-wise values of a 4x4 matrix, where the last row 0,0,0,1 is omitted. We use here the KITTI format; see https://github.com/jbehley/point_labeler/issues/12#issuecomment-570296801 for some explanation.

**Comment by John155** [comment]
Thank you very much for the information
