### ISSUE TITLE
Run on custom dataset

### ISSUE THREAD

**Issue by jagdishbhanushali** [jbehley/SuMa#43]
Thank you for making your work open source. Amazing work. I wanted to generate poses.txt for point cloud annotation tool https://github.com/jbehley/point_labeler. My dataset doesn't have point cloud of 360 view, it only have front point clouds of 120 degree.
When I open my .bin files your tool and click on play button, after 2-3 frames most of point clouds comes on the right side and doesn't very well localize the points.

Do I have to do any configuration to tell the tool that I don't have 360 point cloud, but I have only front 120 degree point clouds.

Thanks,
Jagdish Bhanushali

**Comment by jbehley** [comment]
Not directly and the range image projection does consider the specific setup of the sensor. You definitely have to adapt the parameters, i.e., the field of view, etc. 

However, having only frontal views is not quite optimal as it provides possible very few constraints regarding the map; especially if the sensor is moving fast. (less overlap between map and point cloud) 

It's always hard to say something about the behavior if you don't see the data. Do you have a couple of point clouds that I could use for testing?

In the end, it doesn't matter, how the poses are generated. Therefore, for a quick test, I would suggest using our novel LiDAR odometry method (KISS ICP -> https://github.com/PRBonn/kiss-icp); there we don't assume a specific projection but use directly the point cloud. Especially, @nachovizzo puts significant effort into maintaining KISS-ICP and also has a much nicer way to set up the system (just `pip install kiss-icp` and you're ready to go! :)). 

I would really suggest having a try with KISS, as it has fewer assumptions about the point clouds and works often out of the box.

**Comment by jagdishbhanushali** [comment]
Thank you @jbehley for suggesting KISS-ICP. 
I was able to generate correct poses.txt for point_labeler using KISS-ICP. Really appreciate your quick response.

Thanks,
Jagdish Bhanushali
